### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hugok79** [lxqt/pavucontrol-qt#257] opened 2023-04-18 15:04 UTC
https://github.com/lxqt/pavucontrol-qt/blob/544099248c86ef3c5990264b771d156bfd039c77/src/translations/pavucontrol-qt.ts#L530

Typo in **Propertiesor** !
Should not be **Properties or** ?

**Comment by tsujan** [comment] 2023-04-18 15:30
Duplicate of https://github.com/lxqt/pavucontrol-qt/issues/254

The text has typos but needs to be changed/improved.

**Closed by tsujan** 2023-04-18 15:30 UTC
