### ISSUE TITLE
Lack of 100% stop on volume slider

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pavucontrol-qt#29] opened 2017-03-09 12:53 UTC
In GTK version of pavucontrol sliders have a stop at 100% value with drag snap threshold and graphical mark.

**Comment by pmattern** [comment] 2017-03-13 17:13
Confirmed.
This would indeed be nice to have.

**Comment by palinek** [comment] 2017-03-15 09:08
Please, have a look on the #30. I'm not sure about the snapping to the 100% value. If we set the snap threshold to e.g. 2% points, then use won't be able to set 98%, 99% and 101%, 102% by mouse. Is that something that we want?

**Comment by Vladimir-csp** [comment] 2017-03-15 09:28
In GTK version snap is directional: slider goes:
  ... 98, 99, 100 (snap), 103 (unsnap).
Or
... 103, 102, 101, 100 (snap), 97 (unsnap).

**Comment by palinek** [comment] 2017-03-15 10:30
> In GTK version snap is directional: slider goes:
... 98, 99, 100 (snap), 103 (unsnap).
Or
... 103, 102, 101, 100 (snap), 97 (unsnap).

OK. Implemented in #30

**Comment by pmattern** [comment] 2017-03-15 15:29
I think the snapping can be crossed pretty easily and it wouldn't hurt to miss certain values like 98...102% in favour of a more concise snapping.
Both may of course be a matter of taste.

There is no labelling like the "100% (0dB)" in the GTK version but a tiny vertical line only.
Wouldn't it be good to add this?

**Comment by palinek** [comment] 2017-03-15 15:39
> There is no labelling like the "100% (0dB)" in the GTK version but a tiny vertical line only.
Wouldn't it be good to add this?

Qt (the `QSlider`) doesn't support such feature and IMHO it's not worth implementing it for our purpose.

**Comment by Vladimir-csp** [comment] 2017-03-15 15:42
Precise numerical data is better than no data. But if there are technical issues, then it could go low priority.

**Comment by palinek** [comment] 2017-03-20 07:32
#30 is merged and IMO it is enough. Are we going to close this or leave it open until someone will implement the "ticks labeling" ?

**Comment by pmattern** [comment] 2017-03-20 10:27
> Are we going to close this or leave it open until someone will implement the "ticks labeling" ?

IMO it's not a crucial feature yet good to have. So I'd say leave the issue open if it can basically be implemented without too much effort or other downsides, close otherwise.

**Comment by palinek** [comment] 2017-03-20 10:34
> So I'd say leave the issue open if it can basically be implemented without too much effort

That was my point... I think it will take too much time (at least me with my current knowledge) to implement such tiny feature.

**Comment by tsujan** [comment] 2020-10-05 04:14
As @palinek implied 3 years ago, adding texts to slider tick marks requires a new kind of slider. It isn't worth implementing because it needs a great amount of extra code for such a tiny change.

KDE (and later, Krita) developers created and interesting widget called `KisSliderSpinBox` for the same reason (and more) by combining a part of a sinbox with a progress-bar. Of course, it has no use here.

**Closed by tsujan** 2020-10-05 04:14 UTC
Labels: enhancement
